[build]
builder = "nixpacks"

[deploy]
startCommand = "python manage.py migrate && python manage.py collectstatic --noinput && gunicorn vibemart.wsgi:application"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "never"

[env]
NIXPACKS_PYTHON_VERSION = "3.11" 